apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: {{ .Release.Name }}
spec:
  chart:
    version: {{ .Values.gitlab.version | default .Chart.Version }}
    values:
      gitlab:
        webservice:
          replicaCount: 1
          hpa:
            minReplicas: 1
            maxReplicas: 10
        gitlab-shell:
          replicaCount: 1
          keda:
            enabled: true
            minReplicaCount: 1
            maxReplicaCount: 10
        kas:
          replicaCount: 1
          keda:
            enabled: true
            minReplicaCount: 1
            maxReplicaCount: 10
      registry:
        hpa:
          minReplicas: 1
          maxReplicas: 10
      nginx-ingress:
        enabled: false
      global:
        edition: ce
        pages:
          enabled: true
        gitlab-runner:
          enabled: true
        prometheus:
          install: false
        certmanager:
          install: false
        hosts:
          domain: {{ .Values.gitlab.domain | default "domain.com" }}
        ingress:
          configureCertmanager: {{ if .Values.gitlab.certIssuerEmail }}true{{ else }}false{{ end }}
          class: {{ .Values.gitlab.ingressClassName | default "nginx"}}
      certmanager-issuer:
        email: {{ .Values.gitlab.certIssuerEmail | default "mail@mail.com" }}
