apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  chart:
    version: {{ .Values.gitlab.version | default .Chart.Version }}
    values:
      global:
        edition: ce
        pages:
          enabled: true
        {{- if .Values.serviceAccount }}
        serviceAccount:
          enabled: true
          create: true
          automountServiceAccountToken: true
        {{- end }}
        gitlab-runner:
          enabled: true
        hosts:
          domain: {{ .Values.gitlab.domain | default "domain.com" }}
        ingress:
          configureCertmanager: {{ if .Values.gitlab.certIssuerEmail }}true{{ else }}false{{ end }}
          class: {{ .Values.gitlab.ingressClassName | default "nginx"}}
      certmanager-issuer:
        email: {{ .Values.gitlab.certIssuerEmail | default "mail@mail.com" }}
