{{- if .Values.serviceAccount.create -}}
# gitlab-manager ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitlab.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
# gitlab-app-nonroot ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-app-nonroot
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitlab.labels" . | nindent 4 }}
---
# Role for gitlab-manager
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitlab-manager-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitlab.labels" . | nindent 4 }}
rules:
- apiGroups: ["", "apps", "batch", "autoscaling", "networking.k8s.io"]
  resources:
  - "services"
  - "deployments"
  - "statefulsets"
  - "configmaps"
  - "secrets"
  - "persistentvolumeclaims"
  - "pods"
  - "events"
  - "endpoints"
  - "namespaces"
  - "serviceaccounts"
  - "jobs"
  - "cronjobs"
  - "horizontalpodautoscalers"
  - "ingresses"
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps.gitlab.com"]
  resources: ["gitlabs", "status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["monitoring.coreos.com"]
  resources: 
  - "servicemonitors"
  - "prometheuses"
  - "podmonitors"
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["cert-manager.io"]
  resources:
  - "certificates"
  - "issuers"
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
# RoleBinding for gitlab-manager
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-manager-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitlab.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: gitlab-manager
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: gitlab-manager-role
  apiGroup: rbac.authorization.k8s.io
---
# Role for gitlab-app-nonroot
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitlab-app-role-nonroot
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitlab.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "secrets", "configmaps", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["security.openshift.io"]
  resources: ["securitycontextconstraints", "nonroot-v2"]
  verbs: ["use"]
---
# RoleBinding for gitlab-app-nonroot
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-app-role-nonroot-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitlab.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: gitlab-app-nonroot
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: gitlab-app-role-nonroot
  apiGroup: rbac.authorization.k8s.io
---
# gitlab-nginx-ingress ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-nginx-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitlab.labels" . | nindent 4 }}
---
# Role for gitlab-nginx-ingress
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitlab-nginx-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitlab.labels" . | nindent 4 }}
rules:
- apiGroups: ["networking.k8s.io"]
  resources:
  - "ingresses"
  - "ingressclasses"
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["status"]
  verbs: ["update"]
- apiGroups: ["discovery.k8s.io"]
  resources: ["endpointslices"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["coordination.k8s.io"]
  resources: 
  - "leases"
  - "ingress-controller-leader"
  - "ingress-controller-leader-geo"
  verbs: ["get", "list", "watch", "update", "create"]
- apiGroups: [""]
  resources:
  - "services"
  - "endpoints"
  - "secrets"
  - "pods"
  - "nodes"
  - "namespaces"
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "update", "create"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
# RoleBinding for gitlab-nginx-ingress
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-nginx-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitlab.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: gitlab-nginx-ingress
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: gitlab-nginx-ingress
  apiGroup: rbac.authorization.k8s.io
{{- end }}
