# Secret store is inherited from the minio chart
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Release.Namespace }}-harbor-external-secret"
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: "{{ .Release.Name }}-secret-store"
    kind: SecretStore
  refreshInterval: "1h"
  target:
    name: harbor-s3-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        REGISTRY_STORAGE_S3_ACCESSKEY: "root"
        REGISTRY_STORAGE_S3_SECRETKEY: "{{ `{{ .password }}` }}"
  data:
  - secretKey: password
    remoteRef:
      key: "{{ .Release.Namespace }}-minio-random-password-secret"
      property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Release.Namespace }}-admin-random-passwd-external-secret"
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  target:
    name: "{{ .Release.Namespace }}-admin-random-password-secret"
    creationPolicy: Owner
    deletionPolicy: Delete
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: "{{ .Release.Namespace }}-admin-random-password-generator"
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: "{{ .Release.Namespace }}-admin-random-password-generator"
  namespace: {{ .Release.Namespace }}
spec:
  length: 12
  digits: 5
  symbols: 5
  symbolCharacters: "$@%$#!&"
  noUpper: false
  allowRepeat: false
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Release.Namespace }}-admin-external-secret"
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: "{{ .Release.Name }}-secret-store"
    kind: SecretStore
  refreshInterval: "1h"
  target:
    name: harbor-admin-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        HARBOR_ADMIN_PASSWORD: "{{ `{{ .password }}` }}"
  data:
  - secretKey: password
    remoteRef:
      key: "{{ .Release.Namespace }}-admin-random-password-secret"
      property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Release.Namespace }}-secretkey-random-passwd-external-secret"
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  target:
    name: "{{ .Release.Namespace }}-secretkey-random-password-secret"
    creationPolicy: Owner
    deletionPolicy: Delete
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: "{{ .Release.Namespace }}-secretkey-random-password-generator"
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: "{{ .Release.Namespace }}-secretkey-random-password-generator"
  namespace: {{ .Release.Namespace }}
spec:
  length: 16
  digits: 5
  symbols: 0
  noUpper: false
  allowRepeat: false
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Release.Namespace }}-secretkey-external-secret"
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: "{{ .Release.Name }}-secret-store"
    kind: SecretStore
  refreshInterval: "1h"
  target:
    name: harbor-secretkey-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        secretKey: "{{ `{{ .password }}` }}"
  data:
  - secretKey: password
    remoteRef:
      key: "{{ .Release.Namespace }}-secretkey-random-password-secret"
      property: password
