gitea:
  ingress:
    enabled: false
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
      - host: gitea.domain.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: gitea-tls
        hosts:
          - gitea.domain.com
  persistence:
    size: 5Gi
  gitea:
    admin:
      existingSecret: gitea-admin-secret
  config:
    service:
      DISABLE_REGISTRATION: true

secret-store:
  secretStore:
    clusterWide: false
    provider:
      type: kubernetes
      kubernetes:
        auth:
          serviceAccount:
            create: true
            name: "gitea-secret-store-sa"
