gitea:
  ingress:
    enabled: false
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/proxy-body-size: "2048m"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "1200"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "1200"
    hosts:
      - host: gitea.domain.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: gitea-tls
        hosts:
          - gitea.domain.com
  persistence:
    size: 5Gi
  gitea:
    admin:
      existingSecret: gitea-admin-secret
    config:
      service:
        DISABLE_REGISTRATION: true
        REQUIRE_SIGNIN_VIEW: true
        REGISTER_MANUAL_CONFIRM: false

secret-store:
  secretStore:
    clusterWide: false
    provider:
      type: kubernetes
      kubernetes:
        auth:
          serviceAccount:
            create: true
            name: "gitea-secret-store-sa"
