apiVersion: v2
name: plausible-analytics
description: Plausible-analytics Helm chart configured by Ujstor
type: application
version: 1.0.0
appVersion: "2.0.0"

dependencies:
- name: plausible-analytics
  version: 0.3.3
  repository: https://imio.github.io/helm-charts
- name: secret-store
  version: 1.0.0
  repository: "oci://harbor.k3s0.ujstor.com/helm"
