apiVersion: v2
name: plausible-analytics
description: Plausible-analytics Helm chart configured by Ujstor
type: application
version: 1.0.0
appVersion: "2.1.1"

dependencies:
- name: plausible-analytics
  version: 0.3.3
  repository: https://imio.github.io/helm-charts
- name: secret-store
  version: 1.0.0
  repository: "https://ujstor.github.io/helm-charts-system"
