plausible-analytics:
  baseURL: http://plausible-analytics.local
  totpVaultKey: ""
  image:
    repository: docker.io/plausible/analytics
    tag: "v2.0.0"
  disableRegistration: false
  logFailedLoginAttempts: true

  replicaCount: 1
  image:
    repository: ghcr.io/plausible/community-edition
    pullPolicy: IfNotPresent
    tag: "v2.1.4"

  service:
    type: ClusterIP
    port: 80

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

customIngress:
  enabled: false
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/server-snippets: |
      location / {
        proxy_set_header Upgrade $http_upgrade;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_cache_bypass $http_upgrade;
      }
  hosts:
    - host: plausible-analytics.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: plausible-analytics-tls
      hosts:
        - plausible-analytics.local

secret-store:
  secretStore:
    clusterWide: false
    provider:
      type: kubernetes
      kubernetes:
        auth:
          serviceAccount:
            create: true
            name: "analytics-secret-store-sa"
