baseURL: http://plausible-analytics.local
disableRegistration: false
logFailedLoginAttempts: true

replicaCount: 1
image:
  repository: ghcr.io/plausible/community-edition
  pullPolicy: IfNotPresent
  tag: "v2.1.4"

service:
  type: ClusterIP
  port: 80

customIngress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  hosts:
    - host: plausible-analytics.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: plausible-analytics-tls
      hosts:
        - plausible-analytics.local

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

secret-store:
  secretStore:
    clusterWide: false
    provider:
      type: kubernetes
      kubernetes:
        auth:
          serviceAccount:
            create: true
            name: "analytics-secret-store-sa"
