gitlab:
  version:
  domain: domain.com
  certIssuerEmail: mail@mail.com
  ingressClassName:
  email:
    display_name: 'GitLab'
    from: 'gitlab@example.com'
    reply_to: 'noreply@example.com'
  smtp:
    enabled: true
    address: 'smtp.example.com'
    tls: false
    starttls_auto: true
    port: 587
    authentication: 'plain'
    user_name: 'example'
    password:
      secret: 'smtp-password'
      key: 'password'


# If release ns is not the same as the operator ns
serviceAccount:
    create: true
    annotations: {}

gitlab-runner:
  gitlabUrl: http://gitlab-webservice-default.gitlab.svc.cluster.local:8181  # <svc-name>.<namespace>.svc.cluster.local
  rbac:
    create: true
    rules:
      - apiGroups: [""]
        resources: ["pods", "pods/exec", "pods/attach"]
        verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
      - apiGroups: [""]
        resources: ["secrets"]
        verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
      - apiGroups: [""]
        resources: ["configmaps"]
        verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
      - apiGroups: [""]
        resources: ["services"]
        verbs: ["get", "list", "watch"]
      - apiGroups: [""]
        resources: ["serviceaccounts"]
        verbs: ["get", "list", "watch"]

  concurrent: 10
  runners:
    config: |
      [[runners]]
        [runners.kubernetes]
          namespace = "{{.Release.Namespace}}"
          image = "alpine"
          privileged = true
          service_account = "gitlab-gitlab-runner"
          service_account_overwrite_allowed = "*"
          image_pull_secrets = ["harbor-admin-secret"]
          [[runners.kubernetes.volumes.host_path]]
            name = "buildah"
            mount_path = "/var/lib/containers/"
            read_only = false

  # Name of the secret containing registration token
  # <release-name>-gitlab-runner-secret
  secrets:
    - name: gitlab-gitlab-runner-secret
      items:
        - key: runner-registration-token
          path: runner-registration-token
