gitlab:
  version:
  domain: k3s.ujstor.com
  certIssuerEmail: astipan@gmail.com
  ingressClassName:

serviceAccount: true

# spec:
#   chart:
#     values:

gitlab-runner:
  gitlabUrl:
  runners:
    config: |
      [[runners]]
        [runners.kubernetes]
          namespace = "{{.Release.Namespace}}"
          image = "alpine"

  secrets: []
  # - name: myOtherSecret
  #   items:
  #     - key: key_one
  #       path: path_one
