gitlab:
  version:
  domain: domain.com
  certIssuerEmail: mail@mail.com
  ingressClassName:
  email:
    display_name: 'GitLab'
    from: 'gitlab@example.com'
    reply_to: 'noreply@example.com'
  smtp:
    enabled: true
    address: 'smtp.example.com'
    tls: true
    port: 587
    authentication: 'plain'
    user_name: 'example'
    password:
      secret: 'smtp-password'
      key: 'password'


# If release ns is not the same as the operator ns
serviceAccount:
    create: true
    annotations: {}

gitlab-runner:
  gitlabUrl: http://gitlab-webservice-default.gitlab.svc.cluster.local:8181  # <svc-name>.<namespace>.svc.cluster.local
  rbac:
    create: true
    rules:
      - apiGroups: [""]
        resources: ["pods"]
        verbs: ["get", "list", "watch", "create", "delete"]
      - apiGroups: [""]
        resources: ["pods/exec"]
        verbs: ["create", "patch", "delete"]
      - apiGroups: [""]
        resources: ["pods/attach"]
        verbs: ["list", "get", "create", "delete", "update"]
      - apiGroups: [""]
        resources: ["secrets"]
        verbs: ["list", "get"]
      - apiGroups: [""]
        resources: ["configmaps"]
        verbs: ["list", "get", "create", "delete"]
  concurrent: 10
  runners:
    config: |
      [[runners]]
        [runners.kubernetes]
          namespace = "{{.Release.Namespace}}"
          image = "alpine"
          privileged = false

  # Name of the secret containing registration token
  # <release-name>-gitlab-runner-secret
  secrets:
    - name: gitlab-gitlab-runner-secret
      items:
        - key: runner-registration-token
          path: runner-registration-token
