wordpress:
  wordpressUsername: user
  wordpressPassword: ""
  # NOTE: Must contain key `wordpress-password`
  # NOTE: When it's set, the `wordpressPassword` parameter is ignored
  existingSecret: ""
  wordpressEmail: user@example.com
  wordpressFirstName: FirstName
  wordpressLastName: LastName
  wordpressBlogName: User's Blog!
  wordpressTablePrefix: wp_
  wordpressScheme: http

  replicaCount: 1
  resourcesPreset: "micro"
  # resources:
  #   requests:
  #     cpu: 2
  #     memory: 512Mi
  #   limits:
  #     cpu: 3
  #     memory: 1024Mi

  containerPorts:
    http: 8080
    https: 8443
  service:
    type: ClusterIP
    ports:
      http: 80
      https: 443
    httpsTargetPort: https

  ingress:
    enabled: false
    pathType: Prefix
    ingressClassName: "nginx"
    hostname: wordpress.test.com
    path: /
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    tls: true

  persistence:
    enabled: true
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    accessMode: ReadWriteOnce
    size: 2Gi
    dataSource: {}
    existingClaim: ""
    selector: {}

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 11
    targetCPU: 50
    targetMemory: 50

  mariadb:
    enabled: true
    architecture: standalone
    auth:
      rootPassword: ""
      database: bitnami_wordpress
      username: bn_wordpress
      password: ""
    primary:
      persistence:
        enabled: true
        storageClass: ""
        accessModes:
          - ReadWriteOnce
        size: 2Gi
      resourcesPreset: "micro"
      # resources:
      #   requests:
      #     cpu: 2
      #     memory: 512Mi
      #   limits:
      #     cpu: 3
      #     memory: 1024Mi
      resources: {}
