dockermailserver:
  deployment:
    env:
      OVERRIDE_HOSTNAME: mail.domain.com
  certificate: mailserver-tls

certificates:
  organization: Organization
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: letsencrypt-issuer
    kind: Issuer
