---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: plausible-totp-key
  namespace: plausible
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: SecretStore
    name: "{{ .Release.Namespace }}-secret-store"
  target:
    name: '{{ include "plausible-analytics.fullname" . }}'
    template:
      engineVersion: v2
      data:
        TOTP_VAULT_KEY: "{{ `{{` }} .totp_vault_key | b64enc {{ `}}` }}"
        DATABASE_URL: "postgres://postgres:postgres@{{ .Release.Namespace }}-postgresql:5432/plausible_db"
        CLICKHOUSE_DATABASE_URL: "http://clickhouse:password@{{ .Release.Namespace }}-clickhouse:8123/plausible_events_db"
  data:
    - secretKey: totp_vault_key
      remoteRef:
        key: random-totp-vault-key
        property: totp-vault-key
        decodingStrategy: Base64
    - secretKey: existing
      sourceRef:
        storeRef:
          name: "{{ .Release.Namespace }}-secret-store"
          kind: SecretStore
      remoteRef:
        key: '{{ include "plausible-analytics.fullname" $ }}'

# ---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: plausible-clickhouse
#   namespace: plausible
# spec:
#   refreshInterval: "1h"
#   secretStoreRef:
#     kind: SecretStore
#     name: "{{ .Release.Namespace }}-secret-store"
#   target:
#     name: plausible-clickhouse
#     template:
#       engineVersion: v2
#       data:
#         admin-password: "{{ randAlphaNum 32 | b64enc }}"
#   data:
#     - secretKey: existing
#       sourceRef:
#         storeRef:
#           name: "{{ .Release.Namespace }}-secret-store"
#           kind: SecretStore
#       remoteRef:
#         key: plausible-clickhouse
