---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: plausible-totp-key
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: SecretStore
    name: "{{ .Release.Namespace }}-secret-store"
  target:
    name: '{{ include "plausible-analytics.fullname" . }}'
    template:
      engineVersion: v2
      mergePolicy: Merge
      data:
        DATABASE_URL: "postgres://postgres:postgres@{{ .Release.Namespace }}-postgresql:5432/plausible_db"
        CLICKHOUSE_DATABASE_URL: "http://clickhouse:password@{{ .Release.Namespace }}-clickhouse:8123/plausible_events_db"
  data:
    - secretKey: TOTP_VAULT_KEY
      remoteRef:
        key: random-totp-vault-key
        property: totp-vault-key
    - secretKey: SECRET_KEY_BASE
      remoteRef:
        key: '{{ include "plausible-analytics.fullname" . }}'
        property: SECRET_KEY_BASE
