harbor:
  expose:
    type: ingress
    tls:
      enabled: true
      certSource: secret
      secret:
        secretName: harbor-ingress
    ingress:
      hosts:
        core: harbor.domain.com
      className: "nginx"
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
        nginx.ingress.kubernetes.io/proxy-buffering: "off"
        cert-manager.io/cluster-issuer: "letsencrypt"
        nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
  externalURL: https://harbor.domain.com
  registry:
    relativeurls: true
  persistence:
    enabled: true
    resourcePolicy: "keep"
    persistentVolumeClaim:
      registry:
        accessMode: ReadWriteOnce
        size: 5Gi
      jobservice:
          accessMode: ReadWriteOnce
          size: 1Gi
      database:
        accessMode: ReadWriteOnce
        size: 1Gi
      redis:
        accessMode: ReadWriteOnce
        size: 1Gi
      trivy:
        accessMode: ReadWriteOnce
        size: 5Gi
    imageChartStorage:
      disableredirect: true
      type: s3
      s3:
        existingSecret: harbor-s3-secret
        region: us-east-1
        bucket: harbor-bucket
        regionendpoint: http://minio-harbor-hl.harbor.svc.cluster.local:9000
        secure: false
        skipverify: true
        v4auth: true
        chunksize: "5242880"
        multipartcopychunksize: "33554432"
        multipartcopymaxconcurrency: 100
        rootdirectory: /registry
  existingSecretAdminPassword: harbor-admin-secret
  existingSecretSecretKey: harbor-secretkey-secret
  cache:
    enabled: false
    expireHours: 24
  trivy:
    enabled: true
    gitHubToken: ""
  internalTLS:
    enabled: false
  ipFamily:
    ipv4:
      enabled: true
    ipv6:
      enabled: false

minio-tenant:
  minio-tenant:
    tenant:
      name: minio-harbor
      configuration:
        name: minio-admin-secret
      pools:
        - servers: 1
          name: pool-0
          volumesPerServer: 1
          size: 20Gi
      buckets:
        - name: harbor-bucket
          objectLock: false
          region: us-east-1
