apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Release.Namespace }}-external-secret"
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  target:
    name: gitea-admin-secret
    creationPolicy: Owner
    deletionPolicy: Delete
  secretStoreRef:
    name: "{{ .Release.Namespace }}-secret-store"
    kind: SecretStore
  data:
    - secretKey: username
      template:
        engine: golang
        data: "admin"
    - secretKey: password
      template:
        engine: golang
        data: "{{ randAlphaNum 12 }}{{ randAscii 1 }}{{ randNumeric 3 }}"
