---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Release.Namespace }}-external-secret"
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: "{{ .Release.Name }}-secret-store"
    kind: SecretStore
  target:
    name: gitea-admin-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        username: root
        password: "{{ `{{ .password }}` }}"
  data:
  - secretKey: password
    remoteRef:
      key: "{{ .Release.Namespace }}-gitea-random-password-secret"
      property: password
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Namespace }}-gitea-random-password-secret
spec:
  template:
    spec:
      containers:
      - name: secret-generator
        image: bitnami/kubectl
        command:
        - /bin/sh
        - -c
        - |
          if ! kubectl get secret {{ .Release.Namespace }}-gitea-random-password-secret &>/dev/null; then
            RANDOM_VALUE=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
            kubectl create secret generic {{ .Release.Namespace }}-gitea-random-password-secret --from-literal=password="$RANDOM_VALUE"
            echo "Secret created successfully"
          else
            echo "Secret already exists, skipping creation"
          fi
      serviceAccountName: {{ .Release.Name }}-secret-creator
      restartPolicy: Never
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-secret-creator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-secret-creator
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-creator
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-secret-creator
roleRef:
  kind: Role
  name: {{ .Release.Name }}-secret-creator
  apiGroup: rbac.authorization.k8s.io
