---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Release.Namespace }}-random-passwd-external-secret"
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: "{{ .Release.Namespace }}-secret-store"
    kind: SecretStore
  refreshInterval: "1h"
  target:
    name: "{{ .Release.Namespace }}-random-password-secret"
    creationPolicy: Owner
    deletionPolicy: Delete
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: "random-password"
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: "{{ .Release.Namespace }}-random-password-generator"
  namespace: {{ .Release.Namespace }}
spec:
  length: 12
  digits: 5
  symbols: 5
  symbolCharacters: "$@%$"
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Release.Namespace }}-external-secret"
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: "{{ .Release.Namespace }}-secret-store"
    kind: SecretStore
  refreshInterval: "1h"
  target:
    name: gitea-admin-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        username: admin
        password: "{{ .password }}"
  data:
  - secretKey: password
    remoteRef:
      key: "{{ .Release.Namespace }}-random-password-secret"
      property: password
